#!/bin/sh /etc/rc.common

NAME=vlmcsd
USE_PROCD=1

start_service() {
    procd_open_instance "vlmcsd"

    procd_set_param command /usr/bin/vlmcsd -i /etc/vlmcsd.ini -j /etc/vlmcsd.kmd -l syslog -L 0.0.0.0:1688 -L [::]:1688
    procd_set_param term_timeout 60
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_close_instance
}
