#!/bin/sh /etc/rc.common

START=19
STOP=82
NAME=smartdns
USE_PROCD=1
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
SERVICE_PID_FILE="/var/run/smartdns.pid"

SMARTDNS_CONF="/etc/smartdns/smartdns.conf"

service_triggers() {
	procd_add_reload_trigger firewall
}

load_service()
{
	procd_open_instance "smartdns"

    system_zonename=$(uci -q get system.@system[0].zonename)
	[ -z "$system_zonename" ] || procd_set_param env TZ="$system_zonename"

	procd_set_param command /usr/sbin/smartdns -f -c $SMARTDNS_CONF $args
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param file "$SMARTDNS_CONF"
	procd_set_param term_timeout 60
	procd_close_instance
}
