#!/bin/sh /etc/rc.common

START=18
STOP=83
NAME=detour
USE_PROCD=1

start_service() {
    procd_open_instance "detour"

    procd_set_param command /usr/bin/detour -p 127.0.0.53:53 -f magpie:5353 -4 /etc/detour/china.txt -6 /etc/detour/china6.txt -a 127.0.0.1:5353
    procd_set_param file /etc/detour/china.txt
    procd_set_param file /etc/detour/china6.txt
    procd_set_param term_timeout 60
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_close_instance
}
