#!/bin/sh /etc/rc.common

START=19
STOP=82
NAME=smartdns
USE_PROCD=1

start_service() {
    procd_open_instance "smartdns"

    local system_timezone=$(uci -q get system.@system[0].timezone)
    [ -z "$system_timezone" ] || procd_set_param env TZ="$system_timezone"

    procd_set_param command /usr/sbin/smartdns -f -p - -c /etc/smartdns/smartdns.conf
    procd_set_param file /etc/smartdns/smartdns.conf
    procd_set_param term_timeout 60
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

    procd_close_instance
}
